Return-Path: <linux-spdx-owner@vger.kernel.org>
X-Original-To: lists+linux-spdx@lfdr.de
Delivered-To: lists+linux-spdx@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 5D75753EEFE
	for <lists+linux-spdx@lfdr.de>; Mon,  6 Jun 2022 21:58:49 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S232761AbiFFT6q (ORCPT <rfc822;lists+linux-spdx@lfdr.de>);
        Mon, 6 Jun 2022 15:58:46 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:53628 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S232799AbiFFT6p (ORCPT
        <rfc822;linux-spdx@vger.kernel.org>); Mon, 6 Jun 2022 15:58:45 -0400
Received: from galois.linutronix.de (Galois.linutronix.de [IPv6:2a0a:51c0:0:12e:550::1])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 8F8AD1FCC5
        for <linux-spdx@vger.kernel.org>; Mon,  6 Jun 2022 12:58:44 -0700 (PDT)
Message-ID: <20220606195512.641670264@linutronix.de>
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=linutronix.de;
        s=2020; t=1654545523;
        h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
         to:to:cc:mime-version:mime-version:content-type:content-type:
         content-transfer-encoding:content-transfer-encoding;
        bh=uM+0d9Hmm2x0diVtzfe9FqnCD+ICSAnttL66xVnX3rE=;
        b=KLvExcrCyWGyvEI16ewJeSfZDXGhfMzqxsazg8frSU5IjoRgg/+xa8qUIfzZWnNC5iozA+
        ynB2mj1n9oFiGj7DjHmV/lT5uij23vNyfMlLwHX/7BxvJDC8aUqRkh+NnHSKuuZqfaAK6V
        0ePRsZEqvF2lX25QsSz+R6t2fg14FJ05zBWPasxh4rRp382YzVGZm2+blDvba4dFjN5fqj
        vIklvo4vHo8S5OwpP4q674Y95prwIewlo+XjDiKScC4XsXvNOQJjbwIl8CwAcebEn78a44
        GYTaSY6gfnBn01VMqG74YuDaE/3mGQ0wygiR6DlEjdHMqDGvPVJIjFhE8shh9Q==
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=linutronix.de;
        s=2020e; t=1654545523;
        h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
         to:to:cc:mime-version:mime-version:content-type:content-type:
         content-transfer-encoding:content-transfer-encoding;
        bh=uM+0d9Hmm2x0diVtzfe9FqnCD+ICSAnttL66xVnX3rE=;
        b=Df+lIq55FoPSYwq6zd/K+qK3vO8vT3HcPJSzWE1yhhszaVRtKWqnsP12pO/omXZ42J+LaD
        VeTDper6QVdGC4Aw==
From:   Thomas Gleixner <tglx@linutronix.de>
To:     linux-spdx@vger.kernel.org
Subject: [Batch 1 - patch 13/25] treewide: Replace GPLv2 boilerplate/reference
 with SPDX - gpl-2.0_240.RULE
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Date:   Mon,  6 Jun 2022 21:58:42 +0200 (CEST)
X-Spam-Status: No, score=-4.4 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_MED,SPF_HELO_NONE,
        SPF_PASS,T_SCC_BODY_TEXT_LINE autolearn=ham autolearn_force=no
        version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-spdx.vger.kernel.org>
X-Mailing-List: linux-spdx@vger.kernel.org

Rm9sa3MhClJlZmVyZW5jZXM6IDwyMDIyMDYwNjE5NDA0Mi40Mjg1Njg5MzJAbGludXRyb25peC5k
ZT4KTUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiB0ZXh0L3BsYWluOyBjaGFyc2V0PVVU
Ri04CgpCYXNlZCBvbiB0aGUgbm9ybWFsaXplZCBwYXR0ZXJuOgoKICAgIHRoaXMgcHJvZ3JhbSBp
cyBmcmVlIHNvZnR3YXJlIHlvdSBjYW4gcmVkaXN0cmlidXRlIGl0IGFuZC9vciBtb2RpZnkgaXQK
ICAgIHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGUgZ251IGdlbmVyYWwgcHVibGljIGxpY2Vuc2UgYXMg
cHVibGlzaGVkIGJ5IHRoZQogICAgZnJlZSBzb2Z0d2FyZSBmb3VuZGF0aW9uIHZlcnNpb24gMiBv
ZiB0aGUgbGljZW5zZSAgdGhpcyBwcm9ncmFtIGlzCiAgICBkaXN0cmlidXRlZCBpbiB0aGUgaG9w
ZSB0aGF0IGl0IHdpbGwgYmUgdXNlZnVsIGJ1dCB3aXRob3V0IGFueQogICAgd2FycmFudHkgd2l0
aG91dCBldmVuIHRoZSBpbXBsaWVkIHdhcnJhbnR5IG9mIG1lcmNoYW50YWJpbGl0eSBvcgogICAg
Zml0bmVzcyBmb3IgYSBwYXJ0aWN1bGFyIHB1cnBvc2Ugc2VlIHRoZSBnbnUgZ2VuZXJhbCBwdWJs
aWMgbGljZW5zZQogICAgZm9yIG1vcmUgZGV0YWlscyAgbm8gd2FycmFudHkgdGhlIHByb2dyYW0g
aXMgcHJvdmlkZWQgb24gYW4gYXMgaXMKICAgIGJhc2lzIHdpdGhvdXQgd2FycmFudGllcyBvciBj
b25kaXRpb25zIG9mIGFueSBraW5kIGVpdGhlciBleHByZXNzIG9yCiAgICBpbXBsaWVkIGluY2x1
ZGluZyB3aXRob3V0IGxpbWl0YXRpb24gYW55IHdhcnJhbnRpZXMgb3IgY29uZGl0aW9ucyBvZgog
ICAgdGl0bGUgbm9uLWluZnJpbmdlbWVudCBtZXJjaGFudGFiaWxpdHkgb3IgZml0bmVzcyBmb3Ig
YSBwYXJ0aWN1bGFyCiAgICBwdXJwb3NlIGVhY2ggcmVjaXBpZW50IGlzIHNvbGVseSByZXNwb25z
aWJsZSBmb3IgZGV0ZXJtaW5pbmcgdGhlCiAgICBhcHByb3ByaWF0ZW5lc3Mgb2YgdXNpbmcgYW5k
IGRpc3RyaWJ1dGluZyB0aGUgcHJvZ3JhbSBhbmQgYXNzdW1lcyBhbGwKICAgIHJpc2tzIGFzc29j
aWF0ZWQgd2l0aCBpdHMgZXhlcmNpc2Ugb2YgcmlnaHRzIHVuZGVyIHRoaXMgYWdyZWVtZW50CiAg
ICBpbmNsdWRpbmcgYnV0IG5vdCBsaW1pdGVkIHRvIHRoZSByaXNrcyBhbmQgY29zdHMgb2YgcHJv
Z3JhbSBlcnJvcnMKICAgIGRhbWFnZSB0byBvciBsb3NzIG9mIGRhdGEgcHJvZ3JhbXMgb3IgZXF1
aXBtZW50IGFuZCB1bmF2YWlsYWJpbGl0eSBvcgogICAgaW50ZXJydXB0aW9uIG9mIG9wZXJhdGlv
bnMgIGRpc2NsYWltZXIgb2YgbGlhYmlsaXR5IG5laXRoZXIgcmVjaXBpZW50CiAgICBub3IgYW55
IGNvbnRyaWJ1dG9ycyBzaGFsbCBoYXZlIGFueSBsaWFiaWxpdHkgZm9yIGFueSBkaXJlY3QgaW5k
aXJlY3QKICAgIGluY2lkZW50YWwgc3BlY2lhbCBleGVtcGxhcnkgb3IgY29uc2VxdWVudGlhbCBk
YW1hZ2VzIChpbmNsdWRpbmcKICAgIHdpdGhvdXQgbGltaXRhdGlvbiBsb3N0IHByb2ZpdHMpIGhv
d2V2ZXIgY2F1c2VkIGFuZCBvbiBhbnkgdGhlb3J5IG9mCiAgICBsaWFiaWxpdHkgd2hldGhlciBp
biBjb250cmFjdCBzdHJpY3QgbGlhYmlsaXR5IG9yIHRvcnQgKGluY2x1ZGluZwogICAgbmVnbGln
ZW5jZSBvciBvdGhlcndpc2UpIGFyaXNpbmcgaW4gYW55IHdheSBvdXQgb2YgdGhlIHVzZSBvcgog
ICAgZGlzdHJpYnV0aW9uIG9mIHRoZSBwcm9ncmFtIG9yIHRoZSBleGVyY2lzZSBvZiBhbnkgcmln
aHRzIGdyYW50ZWQKICAgIGhlcmV1bmRlciBldmVuIGlmIGFkdmlzZWQgb2YgdGhlIHBvc3NpYmls
aXR5IG9mIHN1Y2ggZGFtYWdlcwoKZXh0cmFjdGVkIGJ5IHRoZSBzY2FuY29kZSBsaWNlbnNlIHNj
YW5uZXIgdGhlIFNQRFggbGljZW5zZSBpZGVudGlmaWVyCgogICAgR1BMLTIuMC1vbmx5CgpoYXMg
YmVlbiBjaG9zZW4gdG8gcmVwbGFjZSB0aGUgYm9pbGVycGxhdGUvcmVmZXJlbmNlLgoKU2lnbmVk
LW9mZi1ieTogVGhvbWFzIEdsZWl4bmVyIDx0Z2x4QGxpbnV0cm9uaXguZGU+Ci0tLQogZHJpdmVy
cy9zY3NpL3NtYXJ0cHFpL0tjb25maWcgfCAgIDMwICstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLQogMSBmaWxlIGNoYW5nZWQsIDEgaW5zZXJ0aW9uKCspLCAyOSBkZWxldGlvbnMoLSkKCi0t
LSBhL2RyaXZlcnMvc2NzaS9zbWFydHBxaS9LY29uZmlnCisrKyBiL2RyaXZlcnMvc2NzaS9zbWFy
dHBxaS9LY29uZmlnCkBAIC0xLDMgKzEsNCBAQAorIyBTUERYLUxpY2Vuc2UtSWRlbnRpZmllcjog
R1BMLTIuMC1vbmx5CiAjCiAjIEtlcm5lbCBjb25maWd1cmF0aW9uIGZpbGUgZm9yIHRoZSBTTUFS
VFBRSQogIwpAQCAtNywzNSArOCw2IEBACiAjIENvcHlyaWdodCAoYykgMjAxNiBQTUMtU2llcnJh
LCBJbmMuCiAjICAobWFpbHRvOnN0b3JhZ2VkZXZAbWljcm9jaGlwLmNvbSkKIAotIyBUaGlzIHBy
b2dyYW0gaXMgZnJlZSBzb2Z0d2FyZTsgeW91IGNhbiByZWRpc3RyaWJ1dGUgaXQgYW5kL29yCi0j
IG1vZGlmeSBpdCB1bmRlciB0aGUgdGVybXMgb2YgdGhlIEdOVSBHZW5lcmFsIFB1YmxpYyBMaWNl
bnNlCi0jIGFzIHB1Ymxpc2hlZCBieSB0aGUgRnJlZSBTb2Z0d2FyZSBGb3VuZGF0aW9uOyB2ZXJz
aW9uIDIKLSMgb2YgdGhlIExpY2Vuc2UuCi0KLSMgVGhpcyBwcm9ncmFtIGlzIGRpc3RyaWJ1dGVk
IGluIHRoZSBob3BlIHRoYXQgaXQgd2lsbCBiZSB1c2VmdWwsCi0jIGJ1dCBXSVRIT1VUIEFOWSBX
QVJSQU5UWTsgd2l0aG91dCBldmVuIHRoZSBpbXBsaWVkIHdhcnJhbnR5IG9mCi0jIE1FUkNIQU5U
QUJJTElUWSBvciBGSVRORVNTIEZPUiBBIFBBUlRJQ1VMQVIgUFVSUE9TRS4gIFNlZSB0aGUKLSMg
R05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgZm9yIG1vcmUgZGV0YWlscy4KLQotIyBOTyBXQVJS
QU5UWQotIyBUSEUgUFJPR1JBTSBJUyBQUk9WSURFRCBPTiBBTiAiQVMgSVMiIEJBU0lTLCBXSVRI
T1VUIFdBUlJBTlRJRVMgT1IKLSMgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgRUlUSEVSIEVYUFJF
U1MgT1IgSU1QTElFRCBJTkNMVURJTkcsIFdJVEhPVVQKLSMgTElNSVRBVElPTiwgQU5ZIFdBUlJB
TlRJRVMgT1IgQ09ORElUSU9OUyBPRiBUSVRMRSwgTk9OLUlORlJJTkdFTUVOVCwKLSMgTUVSQ0hB
TlRBQklMSVRZIE9SIEZJVE5FU1MgRk9SIEEgUEFSVElDVUxBUiBQVVJQT1NFLiBFYWNoIFJlY2lw
aWVudCBpcwotIyBzb2xlbHkgcmVzcG9uc2libGUgZm9yIGRldGVybWluaW5nIHRoZSBhcHByb3By
aWF0ZW5lc3Mgb2YgdXNpbmcgYW5kCi0jIGRpc3RyaWJ1dGluZyB0aGUgUHJvZ3JhbSBhbmQgYXNz
dW1lcyBhbGwgcmlza3MgYXNzb2NpYXRlZCB3aXRoIGl0cwotIyBleGVyY2lzZSBvZiByaWdodHMg
dW5kZXIgdGhpcyBBZ3JlZW1lbnQsIGluY2x1ZGluZyBidXQgbm90IGxpbWl0ZWQgdG8KLSMgdGhl
IHJpc2tzIGFuZCBjb3N0cyBvZiBwcm9ncmFtIGVycm9ycywgZGFtYWdlIHRvIG9yIGxvc3Mgb2Yg
ZGF0YSwKLSMgcHJvZ3JhbXMgb3IgZXF1aXBtZW50LCBhbmQgdW5hdmFpbGFiaWxpdHkgb3IgaW50
ZXJydXB0aW9uIG9mIG9wZXJhdGlvbnMuCi0KLSMgRElTQ0xBSU1FUiBPRiBMSUFCSUxJVFkKLSMg
TkVJVEhFUiBSRUNJUElFTlQgTk9SIEFOWSBDT05UUklCVVRPUlMgU0hBTEwgSEFWRSBBTlkgTElB
QklMSVRZIEZPUiBBTlkKLSMgRElSRUNULCBJTkRJUkVDVCwgSU5DSURFTlRBTCwgU1BFQ0lBTCwg
RVhFTVBMQVJZLCBPUiBDT05TRVFVRU5USUFMCi0jIERBTUFHRVMgKElOQ0xVRElORyBXSVRIT1VU
IExJTUlUQVRJT04gTE9TVCBQUk9GSVRTKSwgSE9XRVZFUiBDQVVTRUQgQU5ECi0jIE9OIEFOWSBU
SEVPUlkgT0YgTElBQklMSVRZLCBXSEVUSEVSIElOIENPTlRSQUNULCBTVFJJQ1QgTElBQklMSVRZ
LCBPUgotIyBUT1JUIChJTkNMVURJTkcgTkVHTElHRU5DRSBPUiBPVEhFUldJU0UpIEFSSVNJTkcg
SU4gQU5ZIFdBWSBPVVQgT0YgVEhFCi0jIFVTRSBPUiBESVNUUklCVVRJT04gT0YgVEhFIFBST0dS
QU0gT1IgVEhFIEVYRVJDSVNFIE9GIEFOWSBSSUdIVFMgR1JBTlRFRAotIyBIRVJFVU5ERVIsIEVW
RU4gSUYgQURWSVNFRCBPRiBUSEUgUE9TU0lCSUxJVFkgT0YgU1VDSCBEQU1BR0VTCiAKIGNvbmZp
ZyBTQ1NJX1NNQVJUUFFJCiAJdHJpc3RhdGUgIk1pY3JvY2hpcCBQUUkgRHJpdmVyIgoK
